version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development  # Set Flask environment to development
    volumes:
      - .:/app  # Mount the current directory on host to /app in the container
    command: ["gunicorn", "-b", "0.0.0.0:8080", "app.app:app"]  # Command to run the application

  # Add more services if your application has multiple components (e.g., databases, queues, etc.)
